// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2-j4tNUlWzIz7MV1S-vsuCOSc8L7fxRU',
    appId: '1:487818616413:web:43d6446489eb5c2b82f7b4',
    messagingSenderId: '487818616413',
    projectId: 'yourteacher-a3e9d',
    authDomain: 'yourteacher-a3e9d.firebaseapp.com',
    storageBucket: 'yourteacher-a3e9d.appspot.com',
    measurementId: 'G-89DQCVNNQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1F0x8LiPVy_uc644hl8JX4-HdoTqFPIM',
    appId: '1:487818616413:android:74352c89c16d25eb82f7b4',
    messagingSenderId: '487818616413',
    projectId: 'yourteacher-a3e9d',
    storageBucket: 'yourteacher-a3e9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBJ4nd6rxBG_FbD7Ox9S8UqlPZqAcTDe0',
    appId: '1:487818616413:ios:a699361f7264fdd982f7b4',
    messagingSenderId: '487818616413',
    projectId: 'yourteacher-a3e9d',
    storageBucket: 'yourteacher-a3e9d.appspot.com',
    iosClientId: '487818616413-ojo5hk6uuf59cidikr0v0rs68tb387n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourTeacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBJ4nd6rxBG_FbD7Ox9S8UqlPZqAcTDe0',
    appId: '1:487818616413:ios:18084e52a6a4eff882f7b4',
    messagingSenderId: '487818616413',
    projectId: 'yourteacher-a3e9d',
    storageBucket: 'yourteacher-a3e9d.appspot.com',
    iosClientId: '487818616413-0n1c0q30nd7v9sv8igpha5hcnp60qqmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourTeacher.RunnerTests',
  );
}
